### ISSUE TITLE
"Error: cannot re-use a name that is still in use" when enabling prometheus with previously already installed Akri.

### ISSUE THREAD

**Issue by ElijahMendez** [project-akri/akri#444]
**Describe the bug**
After installing the Akri demo using microk8s prometheus.enabled cannot be set as true.

**Output of `kubectl get pods,akrii,akric -o wide`**
```
group8edge@group8edge:~$ kubectl get pods,akrii,akric -o wide
NAME                                              READY   STATUS    RESTARTS      AGE     IP             NODE         NOMINATED NODE   READINESS GATES
pod/akri-udev-discovery-daemonset-lkfwj           1/1     Running   0             3h17m   10.1.116.161   group8edge   <none>           <none>
pod/akri-udev-video-090db9-pod                    1/1     Running   0             3h17m   10.1.116.163   group8edge   <none>           <none>
pod/akri-udev-video-da46e8-pod                    1/1     Running   0             3h17m   10.1.116.162   group8edge   <none>           <none>
pod/akri-video-streaming-app-688456678b-wm9dn     1/1     Running   0             3h13m   10.1.116.164   group8edge   <none>           <none>
pod/akri-agent-daemonset-d847m                    1/1     Running   1 (86m ago)   3h17m   10.1.116.160   group8edge   <none>           <none>
pod/akri-controller-deployment-5c4f48d5c9-v449k   1/1     Running   1 (86m ago)   3h17m   10.1.116.159   group8edge   <none>           <none>

NAME                                      CONFIG            SHARED   NODES            AGE
instance.akri.sh/akri-udev-video-da46e8   akri-udev-video   false    ["group8edge"]   3h17m
instance.akri.sh/akri-udev-video-090db9   akri-udev-video   false    ["group8edge"]   3h17m

NAME                                    CAPACITY   AGE
configuration.akri.sh/akri-udev-video   1          3h17m
```

**Kubernetes Version: [e.g. Native Kubernetes 1.19, MicroK8s 1.19, Minikube 1.19, K3s]**

microk8s 1.23.3

**To Reproduce**
1. Install Akri [usb-camera-demo](https://docs.akri.sh/demos/usb-camera-demo)
2.```helm repo add akri-helm-charts https://project-akri.github.io/akri/
      helm install akri akri-helm-charts/akri \
     $AKRI_HELM_CRICTL_CONFIGURATION \
     --set udev.discovery.enabled=true \
     --set udev.configuration.enabled=true \
     --set udev.configuration.name=akri-udev-video \
     --set udev.configuration.discoveryDetails.udevRules[0]='KERNEL=="video[0-9]*"' \
     --set udev.configuration.brokerPod.image.repository="ghcr.io/project-akri/akri/udev-video-broker"
```
4. [ Enabling Prometheus in Akri](https://docs.akri.sh/user-guide/monitoring-with-prometheus)

5. These components can all be automatically created and deployed via Helm by setting --set prometheus.enabled=true when installing Akri.
```
    helm repo add akri-helm-charts https://project-akri.github.io/akri/
    helm install akri akri-helm-charts/akri \
    $AKRI_HELM_CRICTL_CONFIGURATION \
    --set prometheus.enabled=true
```
Resultant Console output:
```
group8edge@group8edge:~$ helm install akri akri-helm-charts/akri \
>     $AKRI_HELM_CRICTL_CONFIGURATION \
>     --set prometheus.enabled=true
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2948/credentials/client.config
Error: cannot re-use a name that is still in use
```

**Expected behavior**
prometheus.enabled would become equal true, or documentation would explain what steps to take when Akri is already installed/running.

**Logs (please share snips of applicable logs)**
 - To get the logs of any pod, run `kubectl get logs <pod name>`
 - To get the logs of a pod that has already terminated, `kubectl get logs <pod name> --previous`
 - If you believe that the problem is with the Kubelet, run `journalctl -u kubelet` or `journalctl -u snap.microk8s.daemon-kubelet` if you are using a MicroK8s cluster.

**Additional context**
I'm just starting to dip my toes into K8s and services, I apologize if this comes off as a really elementary question.

**Comment by ElijahMendez** [comment]
May have been fixed by replacing "install" with upgrade.

https://github.com/helm/helm/issues/3134

**helm upgrade akri akri-helm-charts/akri \
    $AKRI_HELM_CRICTL_CONFIGURATION \
    --set prometheus.enabled=true**

**Comment by ElijahMendez** [comment]
During installation of Prometheus/Grafana I noticed the cameras were no longer avaliable. The show file showed the following.

```
02:31:43: Expected cameras: 10.152.183.154:80+10.152.183.2:80,10.152.183.54:80
02:31:43: 10.43.6.26 - - [07/Feb/2022 02:31:43] "GET /camera_list HTTP/1.1" 200 -
02:31:44: [10.152.183.54:80] Exception Traceback (most recent call last):
File "./streaming.py", line 58, in get_frames
frame = camera_stub.GetFrame(camera_pb2.NotifyRequest())
File "/usr/lib/python3/dist-packages/grpc/_channel.py", line 533, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/usr/lib/python3/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "Connect Failed"
debug_error_string = "{"created":"@1644201104.346098777","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2721,"referenced_errors":[{"created":"@1644201104.346093147","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1644201104.345804126","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":689,"grpc_status":14,"referenced_errors":[{"created":"@1644201104.345757361","description":"Failed to connect to remote host: OS Error","errno":110,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":210,"os_error":"Connection timed out","syscall":"getsockopt(SO_ERROR)","target_address":"ipv4:10.152.183.54:80"}]}]}]}"
>
02:31:44: Expected cameras: 10.152.183.154:80+10.152.183.2:80,10.152.183.54:80
```

Deleting the video-streaming app pod seems to have been a suitable work around, but I'm adding this in case someone else have the error.

**Comment by ElijahMendez** [comment]
Thank you, I thought that may have been the case. I did the steps you provided lastnight and things have been running now without issues for 15 hours. I will close my issue as this has solved the problems I had.
