### ISSUE TITLE
opcua-monitoring-broker fails with BadRequestTimeout

### ISSUE THREAD

**Issue by rido-min** [project-akri/akri#514]
Following the [OPC UA demo](https://docs.akri.sh/demos/opc-thermometer-demo#creating-opc-ua-servers)

## Environment
 Ubuntu 22.04 running on physical hardware
 k3s version v1.24.4+k3s1 (c3f830e9)
 OPC Reference Server, migrated to `net6.0`, running on the host machine without certificates

## AKRI setup

Deployed AKRI with:

```bash
export AKRI_HELM_CRICTL_CONFIGURATION="--set kubernetesDistro=k3s"
helm repo add akri-helm-charts https://project-akri.github.io/akri/
helm install akri akri-helm-charts/akri \
     $AKRI_HELM_CRICTL_CONFIGURATION \
     --set opcua.discovery.enabled=true \
     --set opcua.configuration.enabled=true \
     --set opcua.configuration.name=akri-opcua-monitoring \
     --set opcua.configuration.brokerPod.image.repository="ghcr.io/project-akri/akri/opcua-monitoring-broker" \
     --set opcua.configuration.brokerProperties.IDENTIFIER='Thermometer_Temperature' \
     --set opcua.configuration.brokerProperties.NAMESPACE_INDEX='2' \
     --set opcua.configuration.discoveryDetails.discoveryUrls[0]="opc.tcp://192.168.86.213:62541/Quickstarts/ReferenceServer"
```
> Where `192.168.86.213` is the host ip address

## Failure

The akri-opcua-monitoring pod is created, but fails `BadRequestTimeout`

**Output of `kubectl get pods,akrii,akric -o wide`**

```
NAME                                              READY   STATUS    RESTARTS        AGE   IP           NODE        NOMINATED NODE   READINESS GATES
pod/akri-opcua-discovery-daemonset-8r8k6          1/1     Running   0               20m   10.42.0.92   ridominpc   <none>           <none>
pod/akri-agent-daemonset-5jbfd                    1/1     Running   0               20m   10.42.0.90   ridominpc   <none>           <none>
pod/akri-controller-deployment-77ffdb7f78-kbn5m   1/1     Running   0               20m   10.42.0.91   ridominpc   <none>           <none>
pod/ridominpc-akri-opcua-monitoring-e9b762-pod    1/1     Running   5 (2m47s ago)   20m   10.42.0.93   ridominpc   <none>           <none>

NAME                                            CONFIG                  SHARED   NODES           AGE
instance.akri.sh/akri-opcua-monitoring-e9b762   akri-opcua-monitoring   true     ["ridominpc"]   20m

NAME                                          CAPACITY   AGE
configuration.akri.sh/akri-opcua-monitoring   1          20m
```

## Additional Info, Logs

When connecting to the OPC endpoint from the same machine I'm able to see the expected nodes. (I tried from a docker container, and from a deployed .net app), however when running from the pod I always got the `BadRequestTimeout`

```
.NET Core OPC UA Console Client Start
1 - Create an Application Configuration.
Exception System.IO.DirectoryNotFoundException: Could not find a part of the path '/etc/opcua-certs/client-pki/own/certs'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern)
   at OpcuaNodeMonitoring.MonitoringClient.GetCertificate(String certificateStorePath) in /src/Program.cs:line 172
   at OpcuaNodeMonitoring.MonitoringClient.CreateApplicationConfiguration() in /src/Program.cs:line 195 thrown when trying to use application certificate mounted at /etc/opcua-certs/client-pki/own/certs/. Using no security.
Application certificates not mounted, using unsecure connection with Security Policy None
Client is using a certificate with subject 
2 - Discover endpoints of opc.tcp://192.168.86.213:62541/Quickstarts/ReferenceServer.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:8083
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
Exception: One or more errors occurred. (BadRequestTimeout)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: Microsoft.Hosting.Lifetime[0]
      Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.

```

I enabled logs in Quickstarts.ReferenceServer.Config.xml, and got

```
09/20/2022 18:03:39.553 SECURE CHANNEL CREATED [.NetStandard ServerChannel UA-TCP 1.4.363.0] [ID=323] Connected To: opc.tcp://192.168.86.213:62541/Quickstarts/ReferenceServer [None/None/Binary]
09/20/2022 18:03:39.554 Token #1 activated. CreatedAt = 18:03:39.553 . Lifetime = 60000
09/20/2022 18:03:39.554 Channel 323 in Open state.
09/20/2022 18:03:39.555 Channel 323: SendOpenSecureChannelResponse()
09/20/2022 18:03:39.655 Channel 323: ProcessRequestMessage 1002
09/20/2022 18:03:39.656 Channel 323: SendResponse 1002
09/20/2022 18:03:39.705 TCPSERVERCHANNEL ProcessCloseSecureChannelRequest Socket=TCPSERVERCHANNEL, ChannelId=20988626, TokenId=323
09/20/2022 18:03:39.706 Channel 323 in Closed state.
09/20/2022 18:03:39.706 Channel 323 closed
09/20/2022 18:03:41.556 TCPSERVERCHANNEL Cleanup Socket=03DF28C9, ChannelId=0, TokenId=0, Reason=Id: BadTimeout
```

## Additional Context

Reviewing issues in the OPC server repo, seems that this is related to the certificates used to connect. The only difference I see from running `ghcr.io/project-akri/akri/opcua-monitoring-broker` from docker, or from K3s, is the `kube-root-ca.crt` configMap, not sure if this might be related.

## Suggestions related to this issue

- Any progress to use the [OPC-PLC-Server](https://github.com/azure-samples/iot-edge-opc-plc/) #464 ? (instead of the modified version of NetCoreReferenceServer) 
- The `opcua-monitoring-broker` is hiding the exception stack trace

**Comment by kate-goldenring** [comment]
@rido-min super nitty but what happens if you change the url from `opc.tcp://192.168.86.213:62541/Quickstarts/ReferenceServer` to `opc.tcp://192.168.86.213:62541/Quickstarts/ReferenceServer/` with the trailing forward slash?

**Comment by kate-goldenring** [comment]
> Any progress to use the [OPC-PLC-Server](https://github.com/azure-samples/iot-edge-opc-plc/) https://github.com/project-akri/akri/issues/464 ? (instead of the modified version of NetCoreReferenceServer)

I believe there is no active work being done on this but it is very desired. If you are interested in contributing, it would be a great add.

**Comment by adithyaj** [comment]
@harrison-tin has a PR out here that should fix this, once that gets merged could we try running this again?

**Comment by harrison-tin** [comment]
@rido-min hello! Did you get a chance to try OPC PLC server sample?

**Comment by rido-min** [comment]
nope, sorry.
